apiVersion: v1
kind: Service
metadata:
  name: apa000ser
spec:
  type: NodePort
  selector:
    app: apa000kube
  ports:
    - port: 80          # 서비스 포트
      targetPort: 80    # 파드 포트
      protocol: TCP
      nodePort: 30080   # 노드 포트(30000~32767)